### ISSUE TITLE
Lektion 13: funktionen

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhys/Programmiervorkurs#15]
- Kleines Schaubild, um Signatur zu erklären
- Praxis: Welchen Datentyp gibt istprim zurück, welche Parameter,…
- […] der übergebene String […]
- Die Funktion übernimmt also Quasi Die Funktion von Zeilen 21+22, und der übergebene String ist  variabel, ihr könnt also nach allen möglichen Zahlen fragen.
- Eventuell andere funktion, oder die Funktionsweise erklären.
- Spiel 3: Ein, zwei Beispiele wo das klappen könnte

**Comment by koebi** [comment]
Lektion 13 sollte man vermutlich komplett umschreiben: In eine Lektion, in der erklärt wird, wozu man funktionen braucht (so weil repetitives codeschreiben und so doof ist), und wie das mit den Rückgabewerten funktioniert (ohne auf Parameter einzugehen) und in der nächsten Lektion dann das erste mal Parameter und Signatur einführen.

**Comment by koebi** [comment]
Aus #41: 
Im Funktionen-Teil gibts immer wieder echt viele Nachfragen.
Wir glauben, dass es an folgenden Dingen liegt:

- Rückgabewerte und warum sie cool sind werden ein mal in einem Halbsatz erwähnt
- Parameter und ihre Bennenung haben das gleiche Problem
- Signaturen werden auch nur einmal im Fließtext erwähnt, ein klärendes Diagramm wäre gut

**Comment by friedz** [comment]
wurde in #59 gefixt
