### ISSUE TITLE
Kapitel 2

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhys/Programmiervorkurs#21]
Ursprüngliche Idee:
Kapitel 2 macht C++-Spezifische Dinge, bisher war schon vieles eher c als c++

Sachen, die in Kapitel 2 getan werden könnte:
- Objektorientierung
- Datentypen, die man so braucht
- structs, klassen, …
- -> programmiere ein 4 gewinnt als abschluss

am covis gibts wohl ein gutes oop-script

**Comment by friedz** [comment]
die Idee war hauptsächlich Objektorientierung also Klassen und Vererbung, in dem zusammenhang dan vielleicht auch stucts. Ist aber schwierig da für virtuelle vererbung Pointer benötigt werden die bisher nicht erwähnt werden und nicht trival einzu führen sind

**Comment by friedz** [comment]
Ok so der Plan was wir so Schreiben wollen/sollten

- [ ] `enum`
- [ ] `struct`

- [ ] `class` aber quasi `enum` + Konstruktor
      Den Vorteil von Verschieden Konstruktoren das verschiedene Werte schon von Anfang an gesetzt sind
- [ ] `class` mit Methoden
- [ ] Header Source Trennung mit mehreren Klassen und Kurz auf Objectfiles eingegangen wird
      (kennen die ja schon grob aus Assembler, Kompiler, Linker)
- [ ] Operatoren überladen auch freie Operatoren
      z.B. Eine Vektor Klasse die `*=` mit einem Skalar Überladen hat damit dann `*` Implementiert, das man einen neuen Vektor bekommt und darüber dann einen freien `*` Implementiert der mit umgedreter Reihenfolge geht (also `i * v` statt `v * i`)
- [ ] zum Schluss dann das 4 Gewinnt
