### ISSUE TITLE
gedit nicht auffindbar

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhys/Programmiervorkurs#34]
da könnte man mal ein bisschen ausführlicher berichten, wo man den findet :))

**Comment by friedz** [comment]
Das ist dann auf jeden fall was das man jedes Jahr überprüfen muss ob es noch stimmt

**Comment by friedz** [comment]
wird glaub ich mit #39 schon gefixt muss was reichen sollte

**Comment by koebi** [comment]
fixed in #45
