### ISSUE TITLE
verweis auf lektion 2 in lektion 1 das da shell erklärt wird

### ISSUE THREAD

**Issue by friedz** [FachschaftMathPhys/Programmiervorkurs#37]
in lektion 1 müssen shell befehle benutzt werden die leute verstehen die aber noch nicht

+ es sollte auch ls genant werden das sie die 'helloworld.cpp' auch sehen
+ es sollte gesagt werden das sie die shell dinge nicht verstehen müssen da sie in lektion 2 erklärt werden

**Comment by koebi** [comment]
fixed in #45
