### ISSUE TITLE
Variablentypen deutlicher erklären

### ISSUE THREAD

**Issue by koebi** [FachschaftMathPhys/Programmiervorkurs#55]
Den Leuten ist oft nicht klar, was der Typ einer Variable ist oder was das soll. Ich bin mir des Skripts gerade nicht ganz sicher, aber das könnte man gegebenenfalls deutlicher formulieren.

**Comment by friedz** [comment]
Ja wie wäre es wenn wir nach **Arithmetik** noch eine Lektion **Variablen Typen** oder so einführen dann haben wir schon etwas wofür wir sie verwenden können und können vielleicht auch auf `double` zu `int` Probleme eingehen
