### ISSUE TITLE
Return von main

### ISSUE THREAD

**Issue by jenuk** [FachschaftMathPhys/Programmiervorkurs#61]
In Lektion 16/Warnings wird angesprochen, dass die `main`-Funktion mit `return` vorzeitig beendet wird. Sollten wir vielleicht die `main`-Funktion (generell oder ab dem Funktionenkapitel) mit `return 0` beenden?

**Comment by friedz** [comment]
Das ist schon guter Stil, wir sollten es Eigentlich überall mache

**Comment by friedz** [comment]
wurde in #63 gefixt
